[project]
name = "url-shorten"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
